# Generated by Django 5.1.3 on 2025-01-06 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(verbose_name='Opción')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.', verbose_name='Creado')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('MALE', 'Hombre'), ('FEMALE', 'Mujer'), ('TRANSGENDER', 'Transgénero'), ('AGENDER', 'Asexual'), ('GENDERFLUID', 'Género fluido'), ('NONBINARY', 'Nonbinary'), ('GENDERQUEER', 'Género Queer'), ('NA', 'No quiero especificar')], max_length=12, verbose_name='Género')),
                ('post_code', models.CharField(max_length=5, verbose_name='Código Postal')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='Orden')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('justification', models.TextField(verbose_name='Justificación')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vas', models.SmallIntegerField(verbose_name='EVA')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgcore.option')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.BooleanField(verbose_name='Fumador')),
                ('sports', models.IntegerField(verbose_name='Deportista')),
                ('diabetes', models.BooleanField(verbose_name='Diabetes')),
                ('ms', models.BooleanField(verbose_name='Esclerosis múltiple')),
                ('parkinson', models.BooleanField(verbose_name='Morbus Parkinson')),
                ('acv', models.BooleanField(verbose_name='Accidente cerebrovascular')),
                ('hta', models.BooleanField(verbose_name='Hipertensión arterial')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgcore.participant')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgcore.question'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vas', models.SmallIntegerField(verbose_name='EVA')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgcore.question')),
            ],
        ),
    ]
