# Generated by Django 5.1.3 on 2025-01-06 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.AddField(
            model_name='answers',
            name='yes',
            field=models.BooleanField(default=False, verbose_name='Sí'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoiceanswers',
            name='yes',
            field=models.BooleanField(default=False, verbose_name='Sí'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='acv',
            field=models.BooleanField(default=False, verbose_name='Accidente cerebrovascular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='diabetes',
            field=models.BooleanField(default=False, verbose_name='Diabetes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='hta',
            field=models.BooleanField(default=False, verbose_name='Hipertensión arterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='ms',
            field=models.BooleanField(default=False, verbose_name='Esclerosis múltiple'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='parkinson',
            field=models.BooleanField(default=False, verbose_name='Morbus Parkinson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='Fumador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='sports',
            field=models.IntegerField(default=False, verbose_name='Deportista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(default=False, help_text='Usuario con login', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClinicalProfile',
        ),
    ]
