# Generated by Django 5.1.3 on 2025-02-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgcore', '0003_remove_option_question_remove_answers_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='hash',
            field=models.IntegerField(default=0, verbose_name='Hash'),
            preserve_default=False,
        ),
    ]
